### ISSUE TITLE
PUT to Create?

### ISSUE THREAD

**Issue by DAddYE** [halayli/memqueue#1]
Hi,

first thanks for sharing this awesome project!

I've only one question ATM, why **put** verb to `Create a new queue in memory` ?

**Comment by halayli** [comment]
Thanks!

The reason I used PUT is because of the HTTP definition of this method:

"The PUT method requests that the enclosed entity be stored under the supplied Request-URI. If the Request-URI refers to an already existing resource, the enclosed entity SHOULD be considered as a modified version of the one residing on the origin server. If the Request-URI does not point to an existing resource, and that URI is capable of being defined as a new resource by the requesting user agent, the origin server can create the resource with that URI."

**Comment by DAddYE** [comment]
That makes sense, thanks !
